### ISSUE TITLE
Torch dtype not getting passsed- results in model being loaded twice if not float32

### ISSUE THREAD

**Issue by rawkintrevo** [caikit/caikit-nlp#134]
## Describe the bug

When finetuning, torch_dtype isn't passed to trainer, only float32 is used. If any type other than float32 is used, this results in the model being loaded on GPU twice, and for any but the smallest models, results in OOM errors. 

See this thread for more details. 
https://discuss.huggingface.co/t/why-is-uploaded-model-twice-the-size-of-actual-model/18782/4

## Platform

Please provide details about the environment you are using, including the following:

All

## Sample Code

Please include a minimal sample of the code that will (if possible) reproduce the bug in isolation

```bash
!python caikit-nlp/examples/run_fine_tuning.py --dataset "billsum"  --model_name tiiuae/falcon-rw-1b --num_epochs 1 --output_dir tmp/falcon-1b --batch_size=4 --accumulate_steps 8 --max_source_length 16 --max_target_length 16 --metric rouge --torch_dtype bfloat16
```

## Expected behavior

The user expects to be able to fit larger models in memory when using half precision (compared to full precision).

## Observed behavior

OOM Errors. It is possible to fit larger models in memory using float32 than it is using float16 or bfloat16

## Additional context

I lost my notes, but I'm pretty sure setting this line manually to `bfloat16` when calling bloat16 from the command line, made everything work as expected.

https://github.com/caikit/caikit-nlp/blob/main/caikit_nlp/resources/pretrained_model/base.py#L185

**Comment by gkumbhat** [comment]
Thanks @rawkintrevo , great find. This means the value that is being passed to bootstrap is either wrong or of wrong type. I thought the casting would happen internal to trainer, but looks like that is not the case.


> I lost my notes, but I'm pretty sure setting this line manually to bfloat16 when calling bloat16 from the command line, made everything work as expected.

Do you mean `bfloat16` the string or the `torch.bfloat16` type?  Currently we are passing the `torch.bfloat16` type 🤔🤔 May be there is some issue there.

https://github.com/caikit/caikit-nlp/blob/df9df07efe1e81bdd15c2612197809211db6e457/caikit_nlp/modules/text_generation/text_generation_local.py#L216

Or may be in our example script we are doing bootstrapping there and not passing the dtype 🤔
