### ISSUE TITLE
Verify and document extent of fine-tuning on single A100 GPU

### ISSUE THREAD

**Issue by gkumbhat** [caikit/caikit-nlp#139]
## Description

To help users make decisions on training parameters for fine-tuning, we want to verify the extent of fine-tuning on A100 80GB machine with below configuration:
1. Max source len: 1024, max target len: 256 
2. Batch sizes: 64, 48, .. 

Idea is to figure out how much training can be held in 1 GPU memory. We can document this in our `README.md` file for now by creating a separate section for Parameter recommendation or memory requirement (or something) and adding a subsection for fine-tuning. (we can add for prompt tuning as well in future)

## Acceptance Criteria

- [ ] README is updated with result

**Comment by olson-ibm** [comment]
Using the following values for $BATCH_SIZE: ```[64, 48, 32, 24, 16, 8, 4, 2, 1]```

**4** was successful, **8** failed. Further bisection:

The max batch size that was successfully tuned: **6**
First batch size that failed tuning with an out-of-memory error: **7**

**Job:** 
```
python examples/run_fine_tuning.py --dataset "glue/rte"  --model_name $LLAMA_HOME --num_epochs 1 --output_dir $MODEL_OUTPUT_DIR --batch_size=$BATCH_SIZE --accumulate_steps 16 --max_source_length 1024 --max_target_length 256 --metric rouge --torch_dtype bfloat16
```

How do we want to record this in the README? Add a benchmark section with a table?

The stdout and stderr from all runs is archived, but I don't have a good place to put them to show the work was done. Any suggestions for a project benchmark repo we can reference from the README?

**Comment by gkumbhat** [comment]
@olson-ibm thanks for the experiments. For now, I think lets add a section in the `README.md` with title `Tested Training Configuration` or something with subsection of `fine-tuning` and add the result out found in a table.

**Comment by gkumbhat** [comment]
This was already merged [here](https://github.com/caikit/caikit-nlp/pull/176)
