### ISSUE TITLE
Add extended inferencing parameter for text-generation inference 

### ISSUE THREAD

**Issue by gkumbhat** [caikit/caikit-nlp#140]
## Is your feature request related to a problem? Please describe.

Currently TGIS exposes certain inference time parameters like temperature etc, which we haven't exposed in any of our text-generation modules. This can become limitation for users. This issue is to add those parameters to TGIS backend modules (both text-generation and prompt tuning) and also implement them to "local" backends

TGIS also exposes details about the input like token count in its response. These aren't exposed currently and should be added as well.

### Input params
- [ ] decoding_method (they call it method) 
- [ ] sampling_parameters (they call it sampling) 
- [ ] StoppingCriteria - `max_new_tokens`, `min_new_tokens` already there. `time_limit_millis` one is tricky for local implementation specially.
- [ ] DecodingParameters - This one is tricky for local implementation specially 
- [ ] `truncate_input_tokens` already supported in text_generation_* modules. Not available in peft ones.

#### Output params
- [ ] `input_token_count` - Need to add in `caikit.interfaces.nlp`

**Comment by chakrn** [comment]
@gkumbhat can you close this out if already done?

**Comment by gkumbhat** [comment]
Can be closed as already completed!
