### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by evaline-ju** [caikit/caikit-nlp#15]
## Description

As a caikit-nlp user, I want to be able to build an image with caikit-nlp functionality!

## Acceptance Criteria

- [ ] Add Dockerfile to build an image for caikit-nlp

**Comment by gkumbhat** [comment]
Caikit-nlp is being built by opendatahub with [this Dockerfile](https://github.com/opendatahub-io/caikit-tgis-serving/blob/main/Dockerfile). We will for now not adding a Dockerfile in caikit-nlp to avoid confusion and duplicate work.
