### ISSUE TITLE
Refactor Causal LM batch tokenization

### ISSUE THREAD

**Issue by alex-jw-brooks** [caikit/caikit-nlp#190]
## Description
Currently, batch tokenization for causal LM has a lot of code duplication, as well as its own generation function. This is super gross and error prone; we should consolidate the batched / singular causal LM logic into something cleaner.

Because the batch encoding is stored as a dict of lists, which is pretty inconvenient, it might be more readable to convert to list of dicts, map the common logic, and convert back. If this approach is taken, we should benchmark a bit to ensure the performance drop is acceptable.

## Acceptance Criteria

- [x] Unit tests cover new/changed code
- [x] Examples build against new/changed code
- [x] READMEs are updated
- [x] Type of [semantic version](https://semver.org/) change is identified

**Comment by alex-jw-brooks** [comment]
Will be closed by PR https://github.com/caikit/caikit-nlp/pull/192

**Comment by chakrn** [comment]
Alex said I can close
