### ISSUE TITLE
Remove device arg from .run()

### ISSUE THREAD

**Issue by alex-jw-brooks** [caikit/caikit-nlp#3]
# Background
Currently, the Peft prompt tuning block takes a device override argument for inference ([here](https://github.com/caikit/caikit-nlp/blob/main/caikit_nlp/modules/text_generation/peft_prompt_tuning.py#L157)). This is silly since it's not actually changing the `model` device. Changing the model device at inference time is also a bit unsafe from a parallelism perspective, so we should:

- Not allow the device to be specified by .run()
- Only let the device be specific at:
- [ ] Train time (done)
- [ ] Load time (needs to be added) 

Note: this should be tested with a Causal LM model, because Peft still doesn't support `.generate()` for seq2seq models.

### Acceptance Criteria
- [ ] Device _cannot_ be specified at inference time
- [x] Device can be specified at train time
- [ ] Device can be specified at load time
- [ ] Tests added

**Comment by rawkintrevo** [comment]
@alex-jw-brooks during refactoring what ever "here" links to broke, could you please update at your convenience?

**Comment by alex-jw-brooks** [comment]
Fixed - thanks!

**Comment by chakrn** [comment]
Closing per @rawkintrevo
