### ISSUE TITLE
Consolidate text-generation module with fine-tuning module

### ISSUE THREAD

**Issue by gkumbhat** [caikit/caikit-nlp#81]
## Description

In the first iteration we started with text_generation and fine_tuning being separate module, which becomes a bit confusing because of inoperability of the modules which are meant to perform same task. Additionally we would also need to add TGIS support for fine-tuning, further making these 2 modules similar. 

In this story, we want to combine these 2 modules to provide single interface

## Discussion

Provide detailed discussion here

## Acceptance Criteria

- [ ] Unit tests cover new/changed code
- [ ] Examples build against new/changed code
- [ ] READMEs are updated
- [ ] Type of [semantic version](https://semver.org/) change is identified

**Comment by evaline-ju** [comment]
#96 did not cover fine tuning and #97 was closed in favor of this, so this issue will presumably cover consolidating output streaming functionality as well
