### ISSUE TITLE
Test fine-tuned model with caikit runtime with TGIS backend

### ISSUE THREAD

**Issue by gkumbhat** [caikit/caikit-nlp#85]
## Description

As a <user type>, I want to <do something>, so that I can <accomplish something>

## Discussion

Provide detailed discussion here

## Acceptance Criteria

- [ ] Unit tests cover new/changed code
- [ ] Examples build against new/changed code
- [ ] READMEs are updated
- [ ] Type of [semantic version](https://semver.org/) change is identified

**Comment by deanwampler** [comment]
This is marked closed in https://github.com/orgs/caikit/projects/6/views/2, but not here??
