### ISSUE TITLE
Add NVIDIA Apex installation to support distributed training

### ISSUE THREAD

**Issue by gkumbhat** [caikit/caikit-nlp#89]
## Description

Since we are moving towards using HF Trainer for handling al the distributed training, we need to install NVIDIA Alex which is used to enable distribution. More details can be found here: https://huggingface.co/docs/transformers/v4.30.0/en/main_classes/trainer#transformers.Trainer:~:text=The%20API%20supports%20distributed%20training%20on%20multiple%20GPUs/TPUs%2C%20mixed%20precision%20through%20NVIDIA%20Apex%20and%20Native%20AMP%20for%20PyTorch.

## Discussion

Provide detailed discussion here

## Acceptance Criteria

- [ ] Unit tests cover new/changed code
- [ ] Examples build against new/changed code
- [ ] READMEs are updated
- [ ] Type of [semantic version](https://semver.org/) change is identified

**Comment by chakrn** [comment]
@gkumbhat @alex-jw-brooks @olson-ibm does this still need to be done to support multi GPU pt? If so, does it need further investigation and should it get an owner?

**Comment by chakrn** [comment]
Gaurav says this is already covered by the Torch install. Closing.
